package mutate

import (
	"go/token"
	"strings"
	"testing"
)

func generate(t *testing.T, src string) []Mutant {
	t.Helper()
	fset := token.NewFileSet()
	mutants, err := Generate(fset, "/tmp/x.go", []byte(src))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return mutants
}

func TestGenerateMutators(t *testing.T) {
	tests := []struct {
		name    string
		src     string
		want    []string // "old -> new" pairs, in any order
		mutator string
	}{
		{
			name:    "comparison becomes off-by-one, not obviously wrong",
			src:     "package p\nfunc f(a, b int) bool { return a > b }\n",
			want:    []string{"> -> >="},
			mutator: "conditional",
		},
		{
			name:    "equality flips",
			src:     "package p\nfunc f(a, b int) bool { return a == b }\n",
			want:    []string{"== -> !="},
			mutator: "conditional",
		},
		{
			name:    "logical and becomes or",
			src:     "package p\nfunc f(a, b bool) bool { return a && b }\n",
			want:    []string{"&& -> ||"},
			mutator: "logical",
		},
		{
			name:    "arithmetic flips sign",
			src:     "package p\nfunc f(a, b int) int { return a + b }\n",
			want:    []string{"+ -> -"},
			mutator: "arithmetic",
		},
		{
			name:    "negation is deleted",
			src:     "package p\nfunc f(a bool) bool { return !a }\n",
			want:    []string{"! -> "},
			mutator: "negation",
		},
		{
			name:    "increment becomes decrement",
			src:     "package p\nfunc f() { i := 0; i++; _ = i }\n",
			want:    []string{"++ -> --", "0 -> 1"},
			mutator: "",
		},
		{
			name:    "boolean literals flip",
			src:     "package p\nvar x = true\n",
			want:    []string{"true -> false"},
			mutator: "boolean",
		},
		{
			name:    "integer literal is incremented",
			src:     "package p\nconst maxRetries = 3\n",
			want:    []string{"3 -> 4"},
			mutator: "literal",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mutants := generate(t, tt.src)
			got := make(map[string]bool, len(mutants))
			for _, m := range mutants {
				got[m.Old+" -> "+m.New] = true
			}
			for _, want := range tt.want {
				if !got[want] {
					t.Errorf("missing mutant %q; got %v", want, keys(got))
				}
			}
			if tt.mutator != "" {
				for _, m := range mutants {
					if m.Old+" -> "+m.New == tt.want[0] && m.Mutator != tt.mutator {
						t.Errorf("mutator: want %q, got %q", tt.mutator, m.Mutator)
					}
				}
			}
		})
	}
}

// A mutant that swaps `>` for `<` is caught by any test at all; the interesting
// mutants are the ones a careless test misses.
func TestGenerateDoesNotProduceObviousMutants(t *testing.T) {
	for _, m := range generate(t, "package p\nfunc f(a, b int) bool { return a > b }\n") {
		if m.New == "<" {
			t.Errorf("`> -> <` is too easy to kill; the useful mutant is `> -> >=`")
		}
	}
}

func TestGenerateSkipsGeneratedFiles(t *testing.T) {
	src := "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\nfunc f(a, b int) bool { return a > b }\n"
	if m := generate(t, src); len(m) != 0 {
		t.Errorf("generated files must not be mutated, got %d mutants", len(m))
	}
}

func TestGenerateSkipsNonDecimalAndOversizedLiterals(t *testing.T) {
	src := "package p\nconst (\n\ta = 0x1F\n\tb = 0b1010\n\tc = 9223372036854775807\n)\n"
	for _, m := range generate(t, src) {
		if m.Mutator == "literal" {
			t.Errorf("unexpected literal mutant %s: unreadable or out of range", m)
		}
	}
}

func TestApplySplicesExactlyOneToken(t *testing.T) {
	src := []byte("package p\n\n// keep this comment\nfunc f(a, b int) bool { return a > b }\n")
	mutants := generate(t, string(src))
	if len(mutants) != 1 {
		t.Fatalf("want 1 mutant, got %d", len(mutants))
	}

	got, err := mutants[0].Apply(src)
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	want := "package p\n\n// keep this comment\nfunc f(a, b int) bool { return a >= b }\n"
	if string(got) != want {
		t.Errorf("Apply:\nwant %q\ngot  %q", want, got)
	}
}

// Splicing bytes rather than re-printing the AST is what keeps build constraints
// and comments intact. If this ever regresses, `//go:build` lines start moving
// and mutants silently stop compiling.
func TestApplyPreservesBuildConstraints(t *testing.T) {
	src := []byte("//go:build linux\n\npackage p\n\nfunc f(a, b int) bool { return a && b == true }\n")
	for _, m := range generate(t, string(src)) {
		out, err := m.Apply(src)
		if err != nil {
			t.Fatalf("Apply: %v", err)
		}
		if !strings.HasPrefix(string(out), "//go:build linux\n\npackage p\n") {
			t.Fatalf("mutant %s destroyed the build constraint:\n%s", m, out)
		}
	}
}

func TestApplyRejectsAStaleOffset(t *testing.T) {
	src := []byte("package p\nfunc f(a, b int) bool { return a > b }\n")
	m := generate(t, string(src))[0]

	edited := []byte("package p\nfunc f(a, b int) bool { return a < b }\n")
	if _, err := m.Apply(edited); err == nil {
		t.Fatal("Apply must refuse an offset whose bytes no longer match, not corrupt the file")
	}
}

func TestApplyRejectsAnOutOfRangeOffset(t *testing.T) {
	m := Mutant{File: "x.go", Offset: 1000, Old: ">", New: ">="}
	if _, err := m.Apply([]byte("package p\n")); err == nil {
		t.Fatal("want an error for an offset past the end of the file")
	}
}

func TestClassify(t *testing.T) {
	// classify reads `go test -json` events. The verdict comes from structured
	// fields, not from scanning the text, because a mutant's own test output can
	// contain any of these sentinel phrases.
	buildFail := `{"Action":"output","Package":"p","Output":"# p [p.test]\n"}
{"Action":"output","Package":"p","Output":"./p.go:4:9: invalid operation\n"}
{"Action":"output","Package":"p","Output":"FAIL\tp [build failed]\n"}
{"Action":"fail","Package":"p","FailedBuild":"p [p.test]"}`

	testFail := `{"Action":"run","Test":"TestX"}
{"Action":"output","Test":"TestX","Output":"--- FAIL: TestX (0.00s)\n"}
{"Action":"fail","Test":"TestX"}
{"Action":"fail","Package":"p"}`

	hang := `{"Action":"output","Output":"panic: test timed out after 30s\n"}
{"Action":"fail","Package":"p"}`

	// The two regressions the review found: a genuine KILL whose failure message
	// happens to contain "[build failed]" / "test timed out". The substring
	// classifier misfiled the first as UNCOMPILABLE (dropping it from the score)
	// and the second as TIMEOUT. Neither carries FailedBuild, and the user text is
	// indented — so it must not match the line-anchored timeout panic.
	poisonedBuild := `{"Action":"run","Test":"TestX"}
{"Action":"output","Test":"TestX","Output":"    f_test.go:3: want ok, got \"[build failed]\" in the log\n"}
{"Action":"fail","Test":"TestX"}
{"Action":"fail","Package":"p"}`

	poisonedTimeout := `{"Action":"run","Test":"TestX"}
{"Action":"output","Test":"TestX","Output":"    f_test.go:3: the message mentions test timed out and signal: killed\n"}
{"Action":"fail","Test":"TestX"}
{"Action":"fail","Package":"p"}`

	tests := []struct {
		name string
		out  string
		want Verdict
	}{
		{"compile error", buildFail, Uncompilable},
		{"test failure", testFail, Killed},
		{"timeout panic", hang, TimedOut},
		{"KILL whose message contains [build failed]", poisonedBuild, Killed},
		{"KILL whose message contains test timed out", poisonedTimeout, Killed},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := classify([]byte(tt.out)); got != tt.want {
				t.Errorf("classify: want %s, got %s", tt.want, got)
			}
		})
	}
}

// A mutant that does not compile grades nothing. Counting it as killed would
// inflate the score of a suite that never ran it.
func TestScoreExcludesUncompilableMutants(t *testing.T) {
	results := []Result{
		{Verdict: Killed}, {Verdict: Killed}, {Verdict: Killed},
		{Verdict: Survived},
		{Verdict: TimedOut},
		{Verdict: Uncompilable}, {Verdict: Uncompilable},
	}
	s := Summarize(results)

	if s.Graded() != 5 {
		t.Errorf("graded: want 5 (uncompilable excluded), got %d", s.Graded())
	}
	if want := 80.0; s.Percent() != want { // 4 detected of 5 graded
		t.Errorf("score: want %.1f%%, got %.1f%%", want, s.Percent())
	}
}

func TestScoreOfNothingIsZeroNotNaN(t *testing.T) {
	if got := Summarize(nil).Percent(); got != 0 {
		t.Errorf("want 0, got %v", got)
	}
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
