// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/metrics/v1/metrics.proto

package metricspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_Ingest_FullMethodName       = "/metrics.v1.MetricsService/Ingest"
	MetricsService_IngestStream_FullMethodName = "/metrics.v1.MetricsService/IngestStream"
	MetricsService_Query_FullMethodName        = "/metrics.v1.MetricsService/Query"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricsService is the gRPC transport between agent and server. It offers the
// three RPC styles: unary, bidirectional streaming and server streaming.
type MetricsServiceClient interface {
	// Ingest submits one batch and returns its ack (unary).
	Ingest(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*IngestAck, error)
	// IngestStream is a long-lived bidirectional stream: the client sends batches
	// and the server replies with one IngestAck per batch, carrying the throttle
	// signal back to the sender.
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Batch, IngestAck], error)
	// Query returns the matching (optionally aggregated) metrics as a server
	// stream, one Metric per message.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metric], error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) Ingest(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, MetricsService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Batch, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Batch, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_IngestStreamClient = grpc.BidiStreamingClient[Batch, IngestAck]

func (c *metricsServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Metric], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[1], MetricsService_Query_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, Metric]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_QueryClient = grpc.ServerStreamingClient[Metric]

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// MetricsService is the gRPC transport between agent and server. It offers the
// three RPC styles: unary, bidirectional streaming and server streaming.
type MetricsServiceServer interface {
	// Ingest submits one batch and returns its ack (unary).
	Ingest(context.Context, *Batch) (*IngestAck, error)
	// IngestStream is a long-lived bidirectional stream: the client sends batches
	// and the server replies with one IngestAck per batch, carrying the throttle
	// signal back to the sender.
	IngestStream(grpc.BidiStreamingServer[Batch, IngestAck]) error
	// Query returns the matching (optionally aggregated) metrics as a server
	// stream, one Metric per message.
	Query(*QueryRequest, grpc.ServerStreamingServer[Metric]) error
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) Ingest(context.Context, *Batch) (*IngestAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedMetricsServiceServer) IngestStream(grpc.BidiStreamingServer[Batch, IngestAck]) error {
	return status.Errorf(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedMetricsServiceServer) Query(*QueryRequest, grpc.ServerStreamingServer[Metric]) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).Ingest(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsServiceServer).IngestStream(&grpc.GenericServerStream[Batch, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_IngestStreamServer = grpc.BidiStreamingServer[Batch, IngestAck]

func _MetricsService_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).Query(m, &grpc.GenericServerStream[QueryRequest, Metric]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_QueryServer = grpc.ServerStreamingServer[Metric]

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.v1.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _MetricsService_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _MetricsService_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Query",
			Handler:       _MetricsService_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/metrics/v1/metrics.proto",
}
