// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: proto/metrics/v1/metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType mirrors model.MetricType. UNSPECIFIED (0) is the proto3 zero value
// and is treated as invalid on ingest.
type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_METRIC_TYPE_GAUGE       MetricType = 1
	MetricType_METRIC_TYPE_COUNTER     MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_GAUGE",
		2: "METRIC_TYPE_COUNTER",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"METRIC_TYPE_GAUGE":       1,
		"METRIC_TYPE_COUNTER":     2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metrics_v1_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_proto_metrics_v1_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{0}
}

// Metric is a single measurement, the protobuf twin of model.Metric.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=metrics.v1.MetricType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Batch is a packet of metrics from one agent.
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Batch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// IngestAck is the server's response to a batch. On the bidirectional stream one
// ack is returned per received batch, so a client can react to backpressure.
type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`   // metrics accepted into the pipeline
	Throttled     bool                   `protobuf:"varint,2,opt,name=throttled,proto3" json:"throttled,omitempty"` // pipeline was saturated; the client should back off
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *IngestAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestAck) GetThrottled() bool {
	if x != nil {
		return x.Throttled
	}
	return false
}

// IngestSummary aggregates the outcome of a whole ingest stream. It is not sent
// today (acks are per-batch) but is reserved for a client-streaming variant.
type IngestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       uint64                 `protobuf:"varint,1,opt,name=batches,proto3" json:"batches,omitempty"`
	Metrics       uint64                 `protobuf:"varint,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Throttled     uint64                 `protobuf:"varint,3,opt,name=throttled,proto3" json:"throttled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSummary) Reset() {
	*x = IngestSummary{}
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSummary) ProtoMessage() {}

func (x *IngestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSummary.ProtoReflect.Descriptor instead.
func (*IngestSummary) Descriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *IngestSummary) GetBatches() uint64 {
	if x != nil {
		return x.Batches
	}
	return 0
}

func (x *IngestSummary) GetMetrics() uint64 {
	if x != nil {
		return x.Metrics
	}
	return 0
}

func (x *IngestSummary) GetThrottled() uint64 {
	if x != nil {
		return x.Throttled
	}
	return 0
}

// QueryRequest mirrors storage.Query. Empty from/to mean open bounds; step
// requires agg. limit == 0 means no limit.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Agg           string                 `protobuf:"bytes,5,opt,name=agg,proto3" json:"agg,omitempty"`   // "" | avg | min | max | sum | count | p50 | p90 | p95 | p99
	Step          string                 `protobuf:"bytes,6,opt,name=step,proto3" json:"step,omitempty"` // Go duration string, e.g. "1m"; requires agg
	Limit         uint32                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *QueryRequest) GetAgg() string {
	if x != nil {
		return x.Agg
	}
	return ""
}

func (x *QueryRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *QueryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_metrics_v1_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/metrics/v1/metrics.proto\x12\n" +
	"metrics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.metrics.v1.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\x06labels\x18\x05 \x03(\v2\x1e.metrics.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x05Batch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\ametrics\x18\x02 \x03(\v2\x12.metrics.v1.MetricR\ametrics\"E\n" +
	"\tIngestAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x1c\n" +
	"\tthrottled\x18\x02 \x01(\bR\tthrottled\"a\n" +
	"\rIngestSummary\x12\x18\n" +
	"\abatches\x18\x01 \x01(\x04R\abatches\x12\x18\n" +
	"\ametrics\x18\x02 \x01(\x04R\ametrics\x12\x1c\n" +
	"\tthrottled\x18\x03 \x01(\x04R\tthrottled\"\xb3\x02\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06labels\x18\x02 \x03(\v2$.metrics.v1.QueryRequest.LabelsEntryR\x06labels\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x10\n" +
	"\x03agg\x18\x05 \x01(\tR\x03agg\x12\x12\n" +
	"\x04step\x18\x06 \x01(\tR\x04step\x12\x14\n" +
	"\x05limit\x18\a \x01(\rR\x05limit\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*Y\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11METRIC_TYPE_GAUGE\x10\x01\x12\x17\n" +
	"\x13METRIC_TYPE_COUNTER\x10\x022\xbb\x01\n" +
	"\x0eMetricsService\x122\n" +
	"\x06Ingest\x12\x11.metrics.v1.Batch\x1a\x15.metrics.v1.IngestAck\x12<\n" +
	"\fIngestStream\x12\x11.metrics.v1.Batch\x1a\x15.metrics.v1.IngestAck(\x010\x01\x127\n" +
	"\x05Query\x12\x18.metrics.v1.QueryRequest\x1a\x12.metrics.v1.Metric0\x01B3Z1metrics-system/internal/proto/metricspb;metricspbb\x06proto3"

var (
	file_proto_metrics_v1_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_v1_metrics_proto_rawDescData []byte
)

func file_proto_metrics_v1_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_v1_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_v1_metrics_proto_rawDesc), len(file_proto_metrics_v1_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_v1_metrics_proto_rawDescData
}

var file_proto_metrics_v1_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_metrics_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_metrics_v1_metrics_proto_goTypes = []any{
	(MetricType)(0),               // 0: metrics.v1.MetricType
	(*Metric)(nil),                // 1: metrics.v1.Metric
	(*Batch)(nil),                 // 2: metrics.v1.Batch
	(*IngestAck)(nil),             // 3: metrics.v1.IngestAck
	(*IngestSummary)(nil),         // 4: metrics.v1.IngestSummary
	(*QueryRequest)(nil),          // 5: metrics.v1.QueryRequest
	nil,                           // 6: metrics.v1.Metric.LabelsEntry
	nil,                           // 7: metrics.v1.QueryRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_metrics_v1_metrics_proto_depIdxs = []int32{
	0,  // 0: metrics.v1.Metric.type:type_name -> metrics.v1.MetricType
	8,  // 1: metrics.v1.Metric.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 2: metrics.v1.Metric.labels:type_name -> metrics.v1.Metric.LabelsEntry
	1,  // 3: metrics.v1.Batch.metrics:type_name -> metrics.v1.Metric
	7,  // 4: metrics.v1.QueryRequest.labels:type_name -> metrics.v1.QueryRequest.LabelsEntry
	8,  // 5: metrics.v1.QueryRequest.from:type_name -> google.protobuf.Timestamp
	8,  // 6: metrics.v1.QueryRequest.to:type_name -> google.protobuf.Timestamp
	2,  // 7: metrics.v1.MetricsService.Ingest:input_type -> metrics.v1.Batch
	2,  // 8: metrics.v1.MetricsService.IngestStream:input_type -> metrics.v1.Batch
	5,  // 9: metrics.v1.MetricsService.Query:input_type -> metrics.v1.QueryRequest
	3,  // 10: metrics.v1.MetricsService.Ingest:output_type -> metrics.v1.IngestAck
	3,  // 11: metrics.v1.MetricsService.IngestStream:output_type -> metrics.v1.IngestAck
	1,  // 12: metrics.v1.MetricsService.Query:output_type -> metrics.v1.Metric
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_metrics_v1_metrics_proto_init() }
func file_proto_metrics_v1_metrics_proto_init() {
	if File_proto_metrics_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_v1_metrics_proto_rawDesc), len(file_proto_metrics_v1_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_v1_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_v1_metrics_proto_depIdxs,
		EnumInfos:         file_proto_metrics_v1_metrics_proto_enumTypes,
		MessageInfos:      file_proto_metrics_v1_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_v1_metrics_proto = out.File
	file_proto_metrics_v1_metrics_proto_goTypes = nil
	file_proto_metrics_v1_metrics_proto_depIdxs = nil
}
