#include "pcap_shim.h"

/*
 * _cgo_export.h is generated by cgo from the //export directives in this
 * package. It declares tfPacketHandler, whose implementation is Go code.
 */
#include "_cgo_export.h"

int tf_pcap_next(pcap_t *handle, tf_packet *out) {
    struct pcap_pkthdr *hdr;
    const unsigned char *data;

    int res = pcap_next_ex(handle, &hdr, &data);
    if (res == 1) {
        out->caplen  = (int)hdr->caplen;
        out->wirelen = (int)hdr->len;
        out->ts_sec  = (long long)hdr->ts.tv_sec;
        out->ts_usec = (long long)hdr->ts.tv_usec;
        out->data    = data;
    }
    return res;
}

int tf_pcap_loop(pcap_t *handle, int count, uintptr_t user) {
    /*
     * The cast on tfPacketHandler drops the `const` qualifiers that cgo cannot
     * express in an exported Go signature. The handler never writes through
     * either pointer, so the cast narrows nothing that matters.
     *
     * `user` travels as a u_char* because that is the slot pcap_loop gives us.
     * It is an integer wearing a pointer's clothes; nothing ever dereferences
     * it.
     */
    return pcap_loop(handle, count, (pcap_handler)tfPacketHandler,
                     (unsigned char *)user);
}

pcap_t *tf_pcap_open_live(const char *device, int snaplen, int promisc,
                          int timeout_ms, char *errbuf) {
    return pcap_open_live(device, snaplen, promisc, timeout_ms, errbuf);
}

int tf_pcap_compile_and_apply(pcap_t *handle, const char *expr) {
    struct bpf_program program;

    /*
     * optimize=1, netmask unknown: we never write filters that need the
     * netmask (it only matters for "ip broadcast").
     */
    if (pcap_compile(handle, &program, expr, 1, PCAP_NETMASK_UNKNOWN) != 0) {
        return -1;
    }

    int res = pcap_setfilter(handle, &program);

    /*
     * pcap_compile allocates the program; setfilter copies what it needs. The
     * free is unconditional, on the success path too — forgetting it is a leak
     * per filter, which for a long-lived agent that reloads its config is a
     * leak that grows.
     */
    pcap_freecode(&program);
    return res;
}

int tf_add(int a, int b) { return a + b; }

long long tf_sum_bytes(const unsigned char *p, int n) {
    long long sum = 0;
    for (int i = 0; i < n; i++) {
        sum += p[i];
    }
    return sum;
}
